version: '3'

services:
  # Сервис PostgreSQL
  postgres:
    container_name: "postgres"
    image: postgres:16
    restart: unless-stopped
    environment:
      POSTGRES_DB: ${DATABASE_NAME}
      POSTGRES_USER: ${DATABASE_USER}
      POSTGRES_PASSWORD: ${DATABASE_PASSWORD}
    volumes:
      - postgres_storage:/var/lib/postgresql/data
    ports:
      - "5432:5432"
    env_file:
      - .env
    networks:
      - custom



  #Сервис FastAPI
  fastapi:
    container_name: "test_app_example"
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8000:8000"
    depends_on:
      - postgres
    command: bash -c "alembic upgrade heads && uvicorn app.main:app --host 0.0.0.0 --port 8000 --reload"
    #    command: [ "/app/docker/app.sh" ]
    networks:
      - custom
    restart: unless-stopped
    env_file:
      - .env




volumes:
  postgres_storage:


networks:
  custom: