version: "2.23"
services:
  db:
    container_name: 'db'
    image: postgres:14.1-alpine
    restart: always
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=postgres
    ports:
      - "5432:5432"
    networks:
      - custom
    volumes:
      - db_data:/var/lib/postgresql/data
networks:
  custom:
    driver: bridge

volumes:
  db_data:
