global:
  scrape_interval: 15s

  external_labels:
    monitor: 'codelab-monitor'

scrape_configs:
  - job_name: 'prometheus'

    scrape_interval: 5s

    static_configs:
      - targets: ['localhost:9090']

  - job_name: 'fastapi_example'

    scrape_interval: 5s

    static_configs:
      - targets: ['fastapi_example:8000']# название из docker-compose Сервиса FastAPI