name: Mypy

on:
  pull_request:
  push:
    branches: [main, test]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout кода
        uses: actions/checkout@v2

      - name: Установка Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.11'

      - name: Установка зависимостей
        run: |
          python -m pip install --upgrade pip
          pip install mypy

      - name: Анализ кода с помощью mypy
        run: |
          mypy --ignore-missing-imports \
            --exclude '\.git|__pycache__|.*\.yml\.enc|.*/migrations/.*|grafana-dashboard\.json|.*/docker/.*|prometheus\.yml' \
            your_python_file.py

